files:
  type:
    python: [".py"]
    markdown: [".md"]
    javascript: [".js"]
    java: [".java"]
    html: [".html", ".htm"]
    text: [".txt"]

  labels:
    code: [python, javascript, java, html]
    docs: [markdown, html, text]

directories:
  ignore:
    - "__pycache__"
    - "node_modules"
    - "venv"
    - "env"
    - ".venv"
    - ".env"
    - "build"
    - "dist"
    - ".git"
    - ".svn"
    - ".hg"
    - "tmp"

# checker-specific extra configurations
checkers_extra:
  - name: "LLMCheckerDraft"
    prompt: "Here could be some prompt"
    check_name: "LLM draft check"

skip_extensions:
  - ".pyo"
  - ".pyc"
  - ".pyd"
  - ".so"
  - ".dll"
  - ".dylib"
  - ".jpg"
  - ".jpeg"
  - ".png"
  - ".gif"
  - ".bmp"
  - ".ico"
  - ".pdf"
  - ".zip"
  - ".tar"
  - ".gz"
  - ".bz2"
  - ".xz"
  - ".exe"
  - ".bin"
  - ".dat"
  - ".db"
  - ".sqlite"
  - ".woff"
  - ".woff2"
  - ".ttf"
  - ".otf"
  - ".eot"

available_extensions:
  - ".py"
  - ".java"
  - ".js"
  - ".ts"
  - ".c"
  - ".cpp"
  - ".h"
  - ".css"
  - ".json"
  - ".md"
  - ".txt"

llm_template: |
  Please check the code for errors.
  Start your answer with "good" if there are no problems, with "bad" otherwise.
  Please provide a brief description of the problems afterwards.
  The code is here: <<<{code}>>>.
  (Start your answer with "good" if there are no problems, with "bad" otherwise.)

llm_length_limit: 10000
