name: publish

on:
  push:
    tags:
      # Publish on any tag starting with a `v`, e.g., v1.2.3
      - v*

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install Python 3.13
        run: uv python install 3.13
      - name: Build
        run: uv build

        # Check that basic features work and we didn't miss to include crucial files
      - name: Smoke test (wheel)
        run: uv run --isolated --no-project --with dist/*.whl pytest tests -m "not slow"
      - name: Smoke test (source distribution)
        run: uv run --isolated --no-project --with dist/*.tar.gz pytest tests -m "not slow"

      - name: Publish
        run: uv publish
