name: 'tests'  # Fast every-push testing

on:
  push:
    branches: [ "*" ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.8.22"

      - name: Install Dependencies
        run: uv sync --locked

      - name: Run tests
        run: |
            uv run -m pytest --cov=qualiluma tests -m "not slow"
            uv run -m pytest --cov=qualiluma tests --durations=0
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
